### ISSUE TITLE
JS Bin is not saving / uploading my code

### ISSUE THREAD

**Issue by Bellaiza631** [jsbin/issues#2]
I am using Google Chrome to open JS Bin. When open a new bin and write my code it does not save. If I click on share it copy the link but then just show a blank page bin.

**Comment by OzBob** [comment]
If I ctrl-shift-s and then take that link to another browser type. e.g. from Edge to Firefox. The 'Internal Server Error' page is displayed

**Comment by remy** [comment]
Acknowledged. Seeing the same thing.

There's a database field missing causing the exception - though I'm pretty certain the data is actually saved: 

- https://output.jsbin.com/wild-wood-83F (errors)
- https://api.jsbin.com/bin/wild-wood-83F/latest - returns data (via API)

I just need to push a v5 compat change to old jsbin to render the bins.

**Comment by remy** [comment]
Fixed and live - though the existing bins won't work as they're missing the `created` field. They will work once all the new code is deployed.

**Comment by hillct** [comment]
The proposed fix does not seem to resolve the problem. While bins may be saved in the tatabase sense, they're rendered in the 'open...' list using a fragment of the HTML pane associated with that bun, however, when a user attempts to load that bin, an error page is presented "something went wrong' indicating that the bin does not exist (with respect to loading it back up, at any rate).

Separately, new bins need a meta tag description as part of their default HTML, in order to provide enough data to make the bin save/load display meaningful
